# Generated by Django 2.2 on 2019-08-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clf', '0003_auto_20190819_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitimage',
            name='fruit_image',
            field=models.ImageField(upload_to='clf/Images/'),
        ),
    ]
